version: '3.8'

services:
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserverdb
    environment:
      SA_PASSWORD: "passwOrd!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data

networks:
  default:
    name: app_network
    driver: bridge

volumes:
  sqlserver_data:
    name: sqlserver_data